# Generated by Django 3.1.5 on 2021-01-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='profileimages/default.jpg', upload_to='profileimages/'),
        ),
    ]
