# Generated by Django 3.1.5 on 2021-01-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
