# Generated by Django 3.1.5 on 2021-01-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
