# Generated by Django 3.1.5 on 2021-02-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20210131_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tracker.wallet'),
        ),
    ]
